---
# --------------------------------

- name: "Distro specific tasks"
  ansible.builtin.include_tasks:
    file: setup-{{ ct_family }}.yml
  when: ct_family == "redhat" or ct_family == "debian"
  tags: ["ct-fail2ban"]

- name: "Render jail.local config"
  ansible.builtin.template:
    dest: /etc/fail2ban/jail.local
    group: root
    mode: "0600"
    owner: root
    src: jail.local.j2
  register: reg_config
  notify: HandlerRestartFail2ban
  become: true
  tags: ["ct-fail2ban"]

- name: "Configure fail2ban service"
  ansible.builtin.systemd:
    enabled: "{{ fail2ban_svc_enabled }}"
    name: "{{ fail2ban_svc_name }}"
    state: "{{ fail2ban_svc_state }}"
  become: true
  tags: ["ct-fail2ban"]

# --------------------------------
...
