---
# --------------------------------

- name: "Install RedHat packages (with update)"
  ansible.builtin.yum:
    name: "{{ fail2ban_pkgs_common.redhat }}"
    state: "{{ fail2ban_state }}"
    update_cache: "{{ fail2ban_refresh_cache }}"
  become: true
  tags: ["ct-fail2ban"]

# --------------------------------
...
