---
# --------------------------------

- name: HandlerRestartFail2ban
  ansible.builtin.systemd:
    state: restarted
    name: '{{ fail2ban_svc_name }}'
  become: true

# --------------------------------
...
